In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Base_Inadimplencia.xlsx', sheet_name = 'Base')
df

,Idade,Sexo,Escolaridade,Tipo_Moradia,Saldo_Investimento,Saldo_Conta_Corrente,Valor_Emprestimo,Duracao_Emprestimo,Inadimplencia
0,67,M,Graduacao,Propria,Sem investimento,Pouco,1169,6,0
1,22,H,Graduacao,Propria,Pouco,Moderado,5951,48,1
2,49,M,Pos Graduacao,Propria,Pouco,Sem conta,2096,12,0
3,45,M,Graduacao,De favor,Pouco,Pouco,7882,42,0
4,53,M,Graduacao,De favor,Pouco,Pouco,4870,24,1
...,...,...,...,...,...,...,...,...,...
995,31,H,Pos Graduacao,Propria,Pouco,Sem conta,1736,12,0
996,40,M,Ensino Medio,Propria,Pouco,Pouco,3857,30,0
997,38,M,Graduacao,Propria,Pouco,Sem conta,804,12,0
998,23,M,Graduacao,De favor,Pouco,Pouco,1845,45,1
999,27,M,Graduacao,Propria,Moderado,Moderado,4576,45,0